name: MasterDeployCI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      env:
          GITHUB_TOKEN: ${{ secrets.social-dashboard-token }}
      run: |
        git config --global user.email "natthapong41@gmail.com"
        git config --global user.name "Natthapong Jiemjintanarom"
        git remote set-url origin git@github.com:babe124578/social-dashboard.git
        npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
